version: '3.4'

services:
  germanvocabularyapi:
    image: germanvocabularyapi
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "5009:5009"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:5009